# This file was generated by GoReleaser. DO NOT EDIT.
cask "observe-claude" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "6863dad02a9f23a4241c52ad846814f26266a5489ff68cbd3eac15ac487db545"
      url "https://github.com/kritnambutt/observe-claude/releases/download/v#{version}/observe-claude_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1c1b31ee77520fe3a8668b24b16f41ba3a62c2e21d4484ecd16a09c87d44a94b"
      url "https://github.com/kritnambutt/observe-claude/releases/download/v#{version}/observe-claude_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9bb78c72a9d86ff9c1e494f04d715ca259f200426b59967719d010aef7b0a129"
      url "https://github.com/kritnambutt/observe-claude/releases/download/v#{version}/observe-claude_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "93fa1f5d44b381a6a2f590e93996695386fc45e2aee499cd42e8d838d9e89aff"
      url "https://github.com/kritnambutt/observe-claude/releases/download/v#{version}/observe-claude_#{version}_linux_arm64.tar.gz"
    end
  end

  name "observe-claude"
  desc "Local observability for Claude Code sessions"
  homepage "https://github.com/kritnambutt/observe-claude"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "observe-claude"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/observe-claude"]
    end
  end

  # No zap stanza required

end
