# This file was generated by GoReleaser. DO NOT EDIT.
cask "observe-claude" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "04364213df452187fd16554a16b8ae5667c0b94a88a803b82fc1f8e9982bae72"
      url "https://github.com/kritnambutt/observe-claude/releases/download/v#{version}/observe-claude_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3f749abc7f467c711ea57b66c2697860cf41fb0e421792988a48b44560add491"
      url "https://github.com/kritnambutt/observe-claude/releases/download/v#{version}/observe-claude_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5b1605d1444758631eaf8031fc5653d7ca5e39773fd893020e7a149eb81af29c"
      url "https://github.com/kritnambutt/observe-claude/releases/download/v#{version}/observe-claude_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c3821d41342d50c7e41712939f18d70101d399e0c1d4c3d2fcd5bb65b410cb8b"
      url "https://github.com/kritnambutt/observe-claude/releases/download/v#{version}/observe-claude_#{version}_linux_arm64.tar.gz"
    end
  end

  name "observe-claude"
  desc "Local observability for Claude Code sessions"
  homepage "https://github.com/kritnambutt/observe-claude"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "observe-claude"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/observe-claude"]
    end
  end

  # No zap stanza required

end
