# This file was generated by GoReleaser. DO NOT EDIT.
cask "observe-claude" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "c9d18ffd4cd5382221d38e9a79a2bf035c7ca3f34275a3196c3acaf536d6fa05"
      url "https://github.com/kritnambutt/observe-claude/releases/download/v#{version}/observe-claude_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "738774152f4999d1482357ea68366baf4bd95d83a7dd758ac9e6ca18c2ad0d76"
      url "https://github.com/kritnambutt/observe-claude/releases/download/v#{version}/observe-claude_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "98949e1dcdc1f08bf2c1fb4eefabaded103869067f05444e393d49620883ac79"
      url "https://github.com/kritnambutt/observe-claude/releases/download/v#{version}/observe-claude_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "13b57b64aa1d373a81b01a951eb13e6e48b83c971fcab0950194bf3ab249dd26"
      url "https://github.com/kritnambutt/observe-claude/releases/download/v#{version}/observe-claude_#{version}_linux_arm64.tar.gz"
    end
  end

  name "observe-claude"
  desc "Local observability for Claude Code sessions"
  homepage "https://github.com/kritnambutt/observe-claude"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "observe-claude"

  # No zap stanza required

end
